name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Navigate to the backend directory
      run: cd ./backend && pwd
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ${{github.workspace}}/backend/package-lock.json
    - name: Install dependencies
      run: npm install
    - run: |
        touch .env
        echo "${{secrets.PROD_ENV_BACK}}" > .env

  frontend:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd frontend
    - run: npm i
    - run: |
        touch .env
        echo "${{secrets.PROD_ENV_FRONT}}" > .env
