name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: ${{github.workspace}}/backend/package-lock.json
    - name: Install PM2
      run: npm install -g pm2
    - name: Navigate to the backend directory install npm and pm2
      run: cd ./backend && npm install && pm2 start server.js --name=BackendAPI
    - name: PM2 BackendAPI
      run: pm2 restart BackendAPI
    - run: |
        touch .env
        echo "${{secrets.PROD_ENV_BACK}}" > ./backend/.env
    